-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 16:57:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL DEFAULT 'no desc.',
  `Status` VARCHAR(45) NOT NULL DEFAULT 'no status',
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idProducts_UNIQUE` ON `mydb`.`Product` (`idProduct` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `idCategory` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL DEFAULT 'no name',
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
PACK_KEYS = DEFAULT
KEY_BLOCK_SIZE = 1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCategories_UNIQUE` ON `mydb`.`Category` (`idCategory` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ProductCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductCategories` (
  `productID` INT NOT NULL,
  `categoryID` INT NOT NULL,
  PRIMARY KEY (`productID`, `categoryID`),
  CONSTRAINT `product`
    FOREIGN KEY (`productID`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category`
    FOREIGN KEY (`categoryID`)
    REFERENCES `mydb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `category_idx` ON `mydb`.`ProductCategories` (`categoryID` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Product`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Product` (`idProduct`, `ProductName`, `Description`, `Status`) VALUES (1, 'Water', 'Water', 'good');
INSERT INTO `mydb`.`Product` (`idProduct`, `ProductName`, `Description`, `Status`) VALUES (2, 'Banana', 'za', 'az');
INSERT INTO `mydb`.`Product` (`idProduct`, `ProductName`, `Description`, `Status`) VALUES (3, 'Apple', 'za', 'az');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Category` (`idCategory`, `CategoryName`) VALUES (1, 'Food');
INSERT INTO `mydb`.`Category` (`idCategory`, `CategoryName`) VALUES (2, 'Electronic');
INSERT INTO `mydb`.`Category` (`idCategory`, `CategoryName`) VALUES (3, 'gf');

COMMIT;

